### ISSUE TITLE
2020 Ford eTransit: Warning: Module did not accept command 27:60, return code: 4

### ISSUE THREAD

**Issue by mckuss** [Sevenstax/FreeV2G#151]
**Your Setup**
Platform: EVSE
Firmware Version: i.e. V01_01_07
Host Controller Interface: Ethernet
Host: FreeV2G (EVSE_v1.1.7_1) + Own Implementation

**Describe the bug**
Vehicle to Grid Service --> Set Configuration command keep getting result "Malformed data", e.g. :
```Warning: Module did not accept command 27:60, return code: 4```

**To Reproduce**
Whitebeet is connected via ETH to raspberry pi 4, eth0 interface. SLAC starts successfully. I believe the error is something to do with my evse_config (note: We have defined intEnums to make the protocol values a bit clearer. The values are not changed from the example in Application.py)
```python
self.evse_config = {
    "evse_id_DIN": '+1310000001',  # no stars
    "evse_id_ISO": 'US3100000015',
    "protocol": [WHITEBEET_SUPPORTED_PROTOCOLS.DIN70121_2.value, WHITEBEET_SUPPORTED_PROTOCOLS.ISO15118_2.value],  # IntEnum 0,1
    "payment_method": [WHITEBEET_SUPPORTED_PAYMENT_METHODS.external.value],  # IntEnum 0
    "energy_transfer_mode": [ENERGY_TRANSFER_MODES.dc_extended.value],  # IntEnum 1
    "certificate_installation_support": False,  
    "certificate_update_support": False,
}
```

**Expected behavior**
I would expect:
```bash
SLAC matching successful
Set V2G mode to EVSE
Start V2G
"Session started" received
``` 

but instead recieve:
```bash
SLAC matching successful
Set V2G mode to EVSE
v2gEvseSetConfiguration | self.evse_config: {'evse_id_DIN': '+1310000001', 'evse_id_ISO': 'US3100000015', 'protocol': [0, 1], 'payment_method': [0], 'energy_transfer_mode': [1], 'certificate_installation_support': False, 'certificate_update_support': False}
Traceback (most recent call last):
  File "/home/pi/git/py-app/app/main.py", line 267, in <module>
    app.loop()
  File "/home/pi/git/py-app/.venv/lib/python3.9/site-packages/freev2g/Evse.py", line 632, in loop
    return self._handleEvConnected()
  File "/home/pi/git/py-app/.venv/lib/python3.9/site-packages/freev2g/Evse.py", line 84, in _handleEvConnected
    self._handleNetworkEstablished()
  File "/home/pi/git/py-app/app/main.py", line 98, in _handleNetworkEstablished
    self.whitebeet.v2gEvseSetConfiguration(self.evse_config)
  File "/home/pi/git/py-app/.venv/lib/python3.9/site-packages/freev2g/Whitebeet.py", line 1163, in v2gEvseSetConfiguration
    self._sendReceiveAck(self.v2g_mod_id, self.v2g_sub_evse_set_configuration, payload)
  File "/home/pi/git/py-app/.venv/lib/python3.9/site-packages/freev2g/Whitebeet.py", line 193, in _sendReceiveAck
    raise Warning("Module did not accept command {:x}:{:x}, return code: {}".format(mod_id, sub_id, response.payload[0]))
Warning: Module did not accept command 27:60, return code: 4
```

**Logs**
- If using the ethernet port enable the port mirror (see Whitebeet manual chapter *13.3.10 Set Port Mirror State*) and create a Wireshark log of the ethernet traffic between the host and the Whitebeet.
- Create a log of the debug port (J11 UART) of the Whitebeet.
- Attach the log files to this issue
[220213_eTransit_configFail_27_60_ret4_uart.txt](https://github.com/Sevenstax/FreeV2G/files/10726273/220213_eTransit_configFail_27_60_ret4_uart.txt)

**Additional context**
Testing on 2020 Ford eTransit. Same result on BMW i3. 
[220213_eTransit_configFail_27_60_ret4.pcapng.txt](https://github.com/Sevenstax/FreeV2G/files/10726285/220213_eTransit_configFail_27_60_ret4.pcapng.txt)

**Comment by mckuss** [comment]
Note, I have tried with certificate_installation_support, certificate_update_support = True, as well as with the default values for evse_id_DIN, evse_id_ISO. pcapng.txt should be renamed to .pcapng (github attachment issue). 

The issue can be replicated on a Ford eTransit & BMW i3.

CCS1 handle is being used. ETH interface to whitebeet from raspberry pi 4. 

Thanks in advance for your support!

**Comment by mckuss** [comment]
Actually updated software seems to get us past this error, V02_00_01 - thanks! Will reach out if I run into further issues, thank you!
