### ISSUE TITLE
Question: Error opening adapter

### ISSUE THREAD

**Issue by JIN-MIRAE** [Sevenstax/FreeV2G#225]
**Your Question**
Ask your questions here.

Hello,

A error occured like below text.
-----------------------------------
(WB_TEST) C:\Users\oggi1\FreeV2G>WB_TEST\Scripts\python Application.py eth -i eth3 -m C4:93:00:34:D0:2C -r EV
Welcome to Codico Whitebeet EV reference implementation
Initiating framing interface
iface: ETH, name: eth3, mac: C4:93:00:34:D0:2C
WHITE-beet-PI firmware version: V01_00_07
Set the CP mode to EV
Start the CP service
Set the CP state to State B
Set SLAC to EV mode
Start SLAC
Wait until an EVSE connects
EVSE connected
Start SLAC matching
SLAC matching successful
Set V2G mode to EV
Set V2G configuration
Traceback (most recent call last):
  File "C:\Users\oggi1\FreeV2G\Application.py", line 48, in <module>
    ev.loop()
  File "C:\Users\oggi1\FreeV2G\Ev.py", line 686, in loop
    return self._handleEvseConnected()
  File "C:\Users\oggi1\FreeV2G\Ev.py", line 179, in _handleEvseConnected
    self._handleNetworkEstablished()
  File "C:\Users\oggi1\FreeV2G\Ev.py", line 197, in _handleNetworkEstablished
    self.whitebeet.v2gEvSetConfiguration(self.config)
  File "C:\Users\oggi1\FreeV2G\Whitebeet.py", line 582, in v2gEvSetConfiguration
    self._sendReceiveAck(self.v2g_mod_id, self.v2g_sub_ev_set_configuration, payload)
  File "C:\Users\oggi1\FreeV2G\Whitebeet.py", line 194, in _sendReceiveAck
    raise Warning("Module did not accept command {:x}:{:x}, return code: {}".format(mod_id, sub_id, response.payload[0]))
Warning: Module did not accept command 27:a0, return code: 17
Process Process-3:
Traceback (most recent call last):
  File "C:\Users\oggi1\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\oggi1\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\oggi1\FreeV2G\EthernetAdapter.py", line 105, in process_receive
    sniff(filter='ether proto 0x6003 and ether src ' + self.dut_mac, iface=self.sut_interface,
  File "C:\Users\oggi1\FreeV2G\WB_TEST\lib\site-packages\scapy\sendrecv.py", line 1311, in sniff
    sniffer._run(*args, **kwargs)
  File "C:\Users\oggi1\FreeV2G\WB_TEST\lib\site-packages\scapy\sendrecv.py", line 1254, in _run
    session.on_packet_received(p)
  File "C:\Users\oggi1\FreeV2G\WB_TEST\lib\site-packages\scapy\sessions.py", line 109, in on_packet_received
    result = self.prn(pkt)
  File "C:\Users\oggi1\FreeV2G\EthernetAdapter.py", line 91, in pkt_callback
    self.queue_rx.put_nowait(frame)
  File "<string>", line 2, in put_nowait
  File "C:\Users\oggi1\AppData\Local\Programs\Python\Python39\lib\multiprocessing\managers.py", line 808, in _callmethod    conn.send((self._id, methodname, args, kwds))
  File "C:\Users\oggi1\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\oggi1\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 285, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] 파이프가 닫히는 중입니다
Exception ignored in: <function Whitebeet.__del__ at 0x0000020A2AA2FD30>
Traceback (most recent call last):
  File "C:\Users\oggi1\FreeV2G\Whitebeet.py", line 129, in __del__
    self._shutdown()
  File "C:\Users\oggi1\FreeV2G\Whitebeet.py", line 134, in _shutdown
    if self.v2gGetMode() == 1:
  File "C:\Users\oggi1\FreeV2G\Whitebeet.py", line 518, in v2gGetMode
    response = self._sendReceiveAck(self.v2g_mod_id, self.v2g_sub_get_mode, None)
  File "C:\Users\oggi1\FreeV2G\Whitebeet.py", line 190, in _sendReceiveAck
    response = self._sendReceive(mod_id, sub_id, payload)
  File "C:\Users\oggi1\FreeV2G\Whitebeet.py", line 184, in _sendReceive
    raise ConnectionError("Problem with send/receive - Please check your connection!")
ConnectionError: Problem with send/receive - Please check your connection!
-----------------------------------

I did remade virtual environment again and again according to "GitHub readme".
I didn't change the configuration or code of FreeV2G.
But, the error is happening continuously.

Ethernet is connected well, power is supplied well.
What is the problem?

Thank you
Mirae

**Comment by lho-stx** [comment]
Hello @JIN-MIRAE,

You have initial communication between Whitebeet and FreeV2G, your virtual environment seems good. The warning

>Module did not accept command 27:a0, return code: 17

Means that the Whitebeet is not in the state of receiving the V2G set configuration command. Can you try to powercycle the Whitebeet starting FreeV2G. It seems the board is in state after a session failed ungracefully and the Whitebeet configuration is in a bad state. 

If the issue is not resolved, please follow [this guide](https://github.com/Sevenstax/FreeV2G/wiki/guide-creating-log-files) and create wireshark and UART logs. If you have questions regarding the guide please let me know, it is a work in progress but should contain all information to create the requested log files.

Thank you,
lho

**Comment by JIN-MIRAE** [comment]
Fourtunately, the problem has been resloved. thank you.

By the way, I have another question.
I want to set the values of test environment, but GitHub guide only provide a comment "You can set the configuration via a configuration file in json format."
However, in FreeV2G SDK, only 'ev.json' file exist and when I used ev.json file, I could change  parameter of EV.

I want to setting other parameter also, like EVCC ID or environment of EVSE...
Is there another file of json format?
Please let me know that how can i do set the values of test environment.

Thank you

**Comment by lho-stx** [comment]
Hey @JIN-MIRAE,

that are good news! May I ask what the problem was?

Regarding the configuration files:

There will be a new FreeV2G version in the near future (we do final testing right now). It will also include the possibility to use configuration files with EVSE. Until then you can change the parameters in the `Evse.py`file.

Thank you and best regards,
lho

**Comment by JIN-MIRAE** [comment]
That is really really good news!
Thank you for providing that news.

So, if new version of FreeV2G is updated, can I do set DC values & ID?
![image](https://github.com/Sevenstax/FreeV2G/assets/129039253/a2805c1b-7cc5-48eb-8ac4-113d2a7ccd09)

The log of DC values & ID values is printed automatically, but I hope to change them also at test.
Is it possible at new FreeV2G?

Best regards
