### ISSUE TITLE
AssertionError: Frame reception timed out issue

### ISSUE THREAD

**Issue by LiamBattershell** [Sevenstax/FreeV2G#86]
**Your Setup**
Platform: EVSE
Firmware Version: WB-CARRIER-BOARD_EI 1.1
Host Controller Interface: Ethernet
Host: FreeV2G (EV_v1.0.4_0) 

**Describe the bug**
 I'm using the python codebase found on your github but I've run into a problem. I get a framing timeout error and I'm not sure why. The carrier board is currently only connected to the ethernet and the 5v power supply connectors.(ive changed the jumper and it is powering up). Is there anything else I would need to connect to be able to establish the ethernet communications? 

**To Reproduce**
NA

**Expected behavior**
it should go through the ethernet connection steps as follows...
Welcome to Codico Whitebeet EVSE reference implementation
Initiating framing interface
iface: eth0, mac: c4:93:00:22:22:22
Set the CP mode to EVSE
Set the CP duty cycle to 100%
Start the CP service
Start SLAC in EVSE mode
Wait until an EV connects

**Logs**
[frame timeout error log.pcapng.txt](https://github.com/Sevenstax/FreeV2G/files/9645243/frame.timeout.error.log.pcapng.txt)

**Additional context**
[frame timeout error log.pcapng.txt](https://github.com/Sevenstax/FreeV2G/files/9645243/frame.timeout.error.log.pcapng.txt)

```
C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master>python3 Application.py "Realtek USB GbE Family Controller" -m c4:93:00:34:ab:5f -r EVSE
Welcome to Codico Whitebeet EVSE reference implementation
Initiating framing interface
iface: Realtek USB GbE Family Controller, mac: c4:93:00:34:ab:5f
Traceback (most recent call last):
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\Whitebeet.py", line 153, in _sendReceive
    response = self.framing.receive_next_frame(filter_mod=[mod_id, 0xFF], filter_req_id=req_id, timeout=time_end - time_start)
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\FramingInterface.py", line 238, in receive_next_frame
    raise AssertionError("Frame reception timed out")
AssertionError: Frame reception timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\Whitebeet.py", line 101, in __init__
    self.slacStop()
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\Whitebeet.py", line 404, in slacStop
    response = self._sendReceive(self.slac_mod_id, self.slac_sub_stop, None)
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\Whitebeet.py", line 168, in _sendReceive
    raise ConnectionError("Problem with send/receive - Please check your connection!")
ConnectionError: Problem with send/receive - Please check your connection!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\Application.py", line 57, in <module>
    with Evse(args.interface, args.mac) as evse:
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\Evse.py", line 8, in __init__
    self.whitebeet = Whitebeet(iface, mac)
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\Whitebeet.py", line 105, in __init__
    raise ConnectionError("Failed to initialize the framing interface on \"{}\"".format(self.framing.sut_interface))
ConnectionError: Failed to initialize the framing interface on "Realtek USB GbE Family Controller"
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\util.py", line 357, in _exit_function
    p.join()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\popen_spawn_win32.py", line 108, in wait
    res = _winapi.WaitForSingleObject(int(self._handle), msecs)
KeyboardInterrupt
Exception ignored in: <function Whitebeet.__del__ at 0x000001F3078E31F0>
Traceback (most recent call last):
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\Whitebeet.py", line 114, in __del__
    self._shutdown()
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\Whitebeet.py", line 121, in _shutdown
    self.framing.shut_down_interface()
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\FramingInterface.py", line 375, in shut_down_interface
    self.clear_backlog()
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\FramingInterface.py", line 349, in clear_backlog
    self.clear_all_data_frames()
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\FramingInterface.py", line 341, in clear_all_data_frames
    self.drain_data()
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\FramingInterface.py", line 346, in drain_data
    self.sut_adapter.clear_queues()
  File "C:\Users\liam_taengineering\Documents\whitebeet\FreeV2G-master\EthernetAdapter.py", line 154, in clear_queues
    while not self.queue_rx.empty():
  File "<string>", line 2, in empty
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\managers.py", line 806, in _callmethod
    self._connect()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\managers.py", line 793, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 505, in Client
    c = PipeClient(address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 707, in PipeClient
    _winapi.WaitNamedPipe(address, 1000)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by LiamBattershell** [comment]
It turns out the MAC address I was using was incorrect. the to use here is 2 less than the MAC printed on the label. it is working now
